types:
  defaults:
    type: file
    thumb: media/thumb.png
    mime: application/octet-stream
    image:
      filters:
        default: [enableProgressive]
  jpg:
    type: image
    thumb: media/thumb-jpg.png
    mime: image/jpeg
    image: null
  jpe:
    type: image
    thumb: media/thumb-jpg.png
    mime: image/jpeg
    image: null
  jpeg:
    type: image
    thumb: media/thumb-jpg.png
    mime: image/jpeg
    image: null
  png:
    type: image
    thumb: media/thumb-png.png
    mime: image/png
    image: null
  webp:
    type: image
    thumb: media/thumb-webp.png
    mime: image/webp
    image: null
  gif:
    type: animated
    thumb: media/thumb-gif.png
    mime: image/gif
    image: null
  svg:
    type: vector
    thumb: media/thumb-svg.png
    mime: image/svg+xml
    image: null
  bmp:
    type: file
    thumb: media/thumb-bmp.png
    mime: image/bmp
    image: null
  html:
    type: file
    thumb: media/thumb-html.png
    mime: text/html
    image: null
  htm:
    type: file
    thumb: media/thumb-html.png
    mime: text/html
    image: null
  css:
    type: file
    thumb: media/thumb-css.png
    mime: text/css
    image: null
  js:
    type: file
    thumb: media/thumb-js.png
    mime: application/javascript
    image: null
  json:
    type: file
    thumb: media/thumb-json.png
    mime: application/json
    image: null
