title: Kris
default_lang: en
author:
  name: Kris
  email: me@normankristiono.net
taxonomies:
  - category
  - tag
metadata:
  description: 'Resume is a free and responsive theme for **Grav**. Its a port of Resume template by HTML5UP.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
description: 'Funny.. user/config'
website: getgrav.org
address:
  -
    line: '811 Margaret Street'
  -
    line: '28015,'
  -
    line: 'Sugar Land, TX 77478'
contact:
  -
    line: LeoCWilhoit@jourrapide.com
  -
    line: '+34 713-902-8117'
  -
    line: '@LeoCWilhoit'
